POST http://localhost:3001/api/blogs
content-type: application/json

{
  "title": "Travel weekend",
  "author": "Sam Doe",
  "url": "www.github.com/samdoe",
  "likes": 33,
  "userId": "5d2c4fa5df0b4b2280c49490"
}