POST http://localhost:3001/api/blogs
content-type: application/json

{
  "title": "This is the first blog",
  "author": "Veikko Lehmuskorpi",
  "url": "www.github.com/veikkolehmuskorpi",
  "likes": 10
}